services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql-db
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: secret
      - key: APP_URL
        value: https://your-app.onrender.com

  - type: pserv
    name: mysql-db
    env: docker
    dockerfilePath: ./mysql.Dockerfile
    plan: free
    envVars:
      - key: MYSQL_DATABASE
        value: laravel
      - key: MYSQL_ROOT_PASSWORD
        value: secret
