<?php

use App\Support\AdminRoles;
use Database\Seeders\RolesAndPermissionsSeeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

it('seeds shield permissions and gives super-admin full coverage', function () {
    $this->seed(RolesAndPermissionsSeeder::class);

    $permissionCount = Permission::query()->count();
    $superAdmin = Role::findByName(AdminRoles::SUPER_ADMIN);

    expect($permissionCount)->toBeGreaterThan(0);
    expect($superAdmin->permissions()->count())->toBe($permissionCount);
});

it('limits writer permissions to blog workflow essentials', function () {
    $this->seed(RolesAndPermissionsSeeder::class);

    $writer = Role::findByName(AdminRoles::WRITER);

    expect($writer->hasPermissionTo('view_any_blog'))->toBeTrue();
    expect($writer->hasPermissionTo('view_blog'))->toBeTrue();
    expect($writer->hasPermissionTo('create_blog'))->toBeTrue();
    expect($writer->hasPermissionTo('update_blog'))->toBeTrue();

    if (Permission::query()->where('name', 'delete_blog')->exists()) {
        expect($writer->hasPermissionTo('delete_blog'))->toBeFalse();
    }

    if (Permission::query()->where('name', 'view_any_user')->exists()) {
        expect($writer->hasPermissionTo('view_any_user'))->toBeFalse();
    }
});

it('keeps role management scoped away from admin role', function () {
    $this->seed(RolesAndPermissionsSeeder::class);

    $admin = Role::findByName(AdminRoles::ADMIN);

    if (Permission::query()->where('name', 'view_any_role')->exists()) {
        expect($admin->hasPermissionTo('view_any_role'))->toBeFalse();
    }
});

it('keeps settings page scoped to super admin role', function () {
    $this->seed(RolesAndPermissionsSeeder::class);

    if (! Permission::query()->where('name', 'page_Settings')->exists()) {
        $this->markTestSkipped('page_Settings permission was not generated by Shield.');
    }

    $superAdmin = Role::findByName(AdminRoles::SUPER_ADMIN);
    $admin = Role::findByName(AdminRoles::ADMIN);
    $editor = Role::findByName(AdminRoles::EDITOR);
    $writer = Role::findByName(AdminRoles::WRITER);

    expect($superAdmin->hasPermissionTo('page_Settings'))->toBeTrue();
    expect($admin->hasPermissionTo('page_Settings'))->toBeFalse();
    expect($editor->hasPermissionTo('page_Settings'))->toBeFalse();
    expect($writer->hasPermissionTo('page_Settings'))->toBeFalse();
});