name: Build and Deploy Assets

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, ctype, fileinfo, json, tokenizer, curl, openssl, pdo, pdo_mysql, intl, zip, exif
          coverage: none
          
      - name: Trust Git directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory /app

      - name: Set up Composer
        uses: php-actions/composer@v6

      - name: Install PHP dependencies
        run: composer install

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Print working directory
        run: pwd

      - name: Check package-lock.json
        run: |
          git diff --exit-code package-lock.json || (echo "package-lock.json is out of sync. Please update it locally and commit the changes."; exit 1)

      - name: Install JS dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      - name: Commit and push built assets
        run: |
          git config --global user.email "fuad89573@email.com"
          git config --global user.name "Fuad"
          git checkout -B deploy
          git add public/css public/js public/build -f
          git commit -m "🚀 Auto-build assets for deployment"
          git push -f origin deploy